version: "3.9"

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pypi
      POSTGRES_PASSWORD: pypi
      POSTGRES_DB: pypi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

